### ISSUE TITLE
Missing extensions in the launcher

### ISSUE THREAD

**Issue by rsvoboda** [fabric8-launcher/launcher-quarkus#105]
There are few missing extensions in the launcher (src/main/resources/quarkus/extensions.json).
Compared with quarkus-maven-plugin:0.21.1:list-extensions.

Missing extensions
 * quarkus-amazon-dynamodb
 * quarkus-elytron-security-oauth2
 * quarkus-rest-client
 * quarkus-smallrye-reactive-type-converters

quarkus-swagger-ui comes with openapi, we don't want it exposed directly

**Comment by ia3andy** [comment]
@rsvoboda Those extensions need first to be added there:
https://raw.githubusercontent.com/quarkusio/quarkusio.github.io/develop/_data/extensions.yaml

**Comment by rsvoboda** [comment]
REST client covered in https://github.com/quarkusio/quarkusio.github.io/pull/280

Extensions for amazon-dynamodb, elytron-security-oauth2, smallrye-reactive-type-converters covered in https://github.com/quarkusio/quarkusio.github.io/pull/281

**Comment by ia3andy** [comment]
@rsvoboda this has been promoted to production: code.quarkus.io
