### ISSUE TITLE
mvnw is not created in the generated projects

### ISSUE THREAD

**Issue by ia3andy** [fabric8-launcher/launcher-quarkus#15]
All the guides are relying on the fact that `mvnw` is in the project. We need to have a consistant story for the user.

**Comment by ia3andy** [comment]
Here is the discussion we had in Zulip:
Andy Damevin: I noticed when using the Quarkus project generator that the generated project does not contain mvnw. I think, all the guides are relying on mvnw beeing there right?

Georgios Andrianakis: weird, using mvn ... create ... should produce the maven wrapper. I always works for me

Andy Damevin: I mean using the library

Georgios Andrianakis: oh, OK. yeah, the wrapper is added in the mojo

Guillaume Smet: The library is not tied to Maven. That’s why it’s done in the Mojo. Not sure if we could change that without breaking modularity.

Andy Damevin: `.buildTool(BuildTool.MAVEN)`

Georgios Andrianakis: the wrapper itself is generated by a different maven plugin. it could of course exist in the project and just be copied, but the way it's done now makes most sense I think when taking into account how projects are created

Guillaume Smet: Including it in the template could be an option. But it would be harder to maintain for us. Except if it could be installed automatically in the template during the build maybe.

Georgios Andrianakis: Can't the launcher include it?

Andy Damevin: of course we could, is it the best solution, I am not sure

Guillaume Smet: We require a recent version and we had reports of people using old ones until we switched to mvnw

Andy Damevin: Who is supposed to use the java Quarkus build tool? It would be weird IMO, to add some logic that couldn't be used by any consumer of this library

**Comment by ia3andy** [comment]
@stuartwdouglas Here is the issue for the missing `mvnw`. @emmanuelbernard @gsmet, we need to decide how we handle this.

**Comment by emmanuelbernard** [comment]
@ia3andy for the sake of velocity, I think you should create it in the launcher.

Since @aloubyansky and all are working on a gradle add-extension based on an include in the build.gradle, we could sue the opportunity of that being done to then have a "gradle create" and rethink that choice. At this time we will add gradle support in the launcher too.

**Comment by emmanuelbernard** [comment]
Created https://github.com/fabric8-launcher/launcher-quarkus/issues/67
