### ISSUE TITLE
Add blurb about extensions

### ISSUE THREAD

**Issue by ia3andy** [fabric8-launcher/launcher-quarkus#35]
https://github.com/fabric8-launcher/launcher-quarkus/issues/2#issuecomment-507568201

**Comment by ia3andy** [comment]
![image](https://user-images.githubusercontent.com/2223984/61381057-c4224e00-a8aa-11e9-86f9-c97abcdbe5ae.png)

@emmanuelbernard @jasonbrock

**Comment by ia3andy** [comment]
After discussion it with Jason, we thought that adding a click was a bad idea.

So we thought we could split the content of this message, the first part would be as a closable info block in the Extensions section:
> Think of Quarkus extensions as your project dependencies. Extensions configure, boot and integrate a framework or technology into your Quarkus application.
They also do all of the heavy lifting of providing the right information to GraalVM for your application to compile natively.

And the second part would be in the "What's next" modal (after generation):
![image](https://user-images.githubusercontent.com/2223984/61382243-b1107d80-a8ac-11e9-8002-9267d20fc826.png)

It could even be contextual to what type of project as been selected (maven or gradle)

**Comment by ia3andy** [comment]
Jason is preparing a design for the info box..

**Comment by emmanuelbernard** [comment]
This one would be a likely blocker but to ahve some text, better design can wait

**Comment by emmanuelbernard** [comment]
I agree with you that we don't need the quarkus:list-extensions etc on this page. Or less proheminent, that can wait for sure

**Comment by emmanuelbernard** [comment]
+1 to get a foldable blurb approach

**Comment by emmanuelbernard** [comment]
Here is a proposal for a new blurb

```
This page will help you bootstrap your Quarkus application and discover its extensions ecosystem.

Think of Quarkus extensions as your project dependencies. Extensions configure, boot and integrate a framework or technology into your Quarkus application. They also do all of the heavy lifting of providing the right information to GraalVM for your application to compile natively. 

Explore the wide breath of technologies Quarkus applications and generate your project!
```

The middle paragraph could be the foldable part.

Also on the page after the generation, I'd change the text to

```
Your new Quarkus app has been generated

Your download should start shortly. If it doesn't, please use the direct link.
What's next!

Unzip the project and start playing with Quarkus by running `./mvnw compile quarkus:dev`.
Follow the guides for your next steps!
```
to learn more and build a great Quarkus app!
```

**Comment by ia3andy** [comment]
@emmanuelbernard ok thanks, I think this one is really important too: https://github.com/fabric8-launcher/launcher-quarkus/issues/15
