### ISSUE TITLE
Order categories and extensions

### ISSUE THREAD

**Issue by gsmet** [fabric8-launcher/launcher-quarkus#36]
We should follow the order of the current Extensions page: https://quarkus.io/extensions/ .

**Comment by ia3andy** [comment]
I think we should postpone this until we find a proper way to handle the order. Doing it manually doesn't seem like a sain approach to me.

**Comment by emmanuelbernard** [comment]
I would consider it a blocker actually. Even if yiou have to hard code a number -> category name in the code base for now, we need that at launch imo

**Comment by ia3andy** [comment]
@emmanuelbernard noted, I'll add that to my priority list..

Any other blocker you have in mind?
