### ISSUE TITLE
Empty directory levels in zipped archive

### ISSUE THREAD

**Issue by johnaohara** [fabric8-launcher/launcher-quarkus#39]
The created Zip archive contains additional directory levels, e.g. `/src/main/java//org/example//QuarkusApp.java`, or `/src/test/java//org/example//QuarkusAppTest.java`.

When the file is unzipped, the directory structures appear to be created correctly. Browsing the archive with an archive manage lookes like we have emtpy directories

**Comment by ia3andy** [comment]
@johnaohara I am not sure I understand what you mean here. 

FYI, the zip is generated using the quarkus project creator:
https://github.com/fabric8-launcher/launcher-quarkus/blob/master/src/main/kotlin/io/fabric8/launcher/quarkus/LauncherQuarkus.kt#L32

So I guess the bug should maybe be reported there?

**Comment by ia3andy** [comment]
I see two similar issues:
- https://github.com/fabric8-launcher/launcher-quarkus/issues/65
- https://github.com/fabric8-launcher/launcher-quarkus/issues/66

@johnaohara any more info?

**Comment by ia3andy** [comment]
@johnaohara I've noticed this bug too, it seems to be a bug in the quarkus lib creator. I am creating an issue:
https://github.com/quarkusio/quarkus/issues/3348

**Comment by johnaohara** [comment]
Yeah, sorry didn't get back to updating this.

The issue is saw is https://github.com/quarkusio/quarkus/issues/3348, so we could close this down as you are tracking in #66 as well, although not just limited to windows
