### ISSUE TITLE
Choose and setup an analytics system

### ISSUE THREAD

**Issue by ia3andy** [fabric8-launcher/launcher-quarkus#4]

**Comment by ALRubinger** [comment]
Recommend looking into Segment, which acts as an abstraction.  We have an account already though I'm not sure we're getting great data.  The idea is that no matter which analytics service(s) you choose, the code is implemented in Segment and from there hooks into analytics providers and pluggable backends.  @quintesse can get you a tour of what minimal stuff we currently have set up.

**Comment by ia3andy** [comment]
https://github.com/fabric8-launcher/launcher-frontend/pull/1313
