### ISSUE TITLE
Show module dependencies in the "Selected Extensions" area

### ISSUE THREAD

**Issue by mkouba** [fabric8-launcher/launcher-quarkus#41]
The modules depend on each other so it would be nice that if I select a module all its module dependencies are visible in the "Selected Extensions" area and possibly also in the modules area.

For example, if you select "SmallRye Fault Tolerance" your project will automatically depend on ArC, SmallRye Metrics and SmallRye Context Propagation. No need to add them manually.

**Comment by mkouba** [comment]
@ia3andy TBH I'm not sure if it's implementable because you would probably need some module dependencies info in the extensions.json file...

**Comment by FroMage** [comment]
Dupe of #38? :)

**Comment by mkouba** [comment]
@FroMage ah yes, sorry, closing this one. On the other hand, I believe it's quite important part of UX so it should have higher priority ;-)
