### ISSUE TITLE
Setup CI/CD + deployment on Staging & Production

### ISSUE THREAD

**Issue by ia3andy** [fabric8-launcher/launcher-quarkus#6]
CI/CD:
- [x] Setup circle ci to build the docker image
- [x] Setup circle ci to run backend and frontend tests on PRs
- [x] Add PR and review checks

Hosting:
- [x] Find an ops
- [x] Find a server

**Comment by ia3andy** [comment]
The app runs on a single Quarkus image serving the backend and the frontend..

Here is a preview:
http://preview-launcher-quarkus.b9ad.pro-us-east-1.openshiftapps.com/

**Comment by kenfinnigan** [comment]
Is there an easy way to separate the UI if we want that deployed directly to the main website?

**Comment by ia3andy** [comment]
We could yes, but as @gsmet said and I agree:
> I think a specific subdomain would be OK
> the UI will be different anyway
> so I don't see a lot of value in integrating it in the website

**Comment by ia3andy** [comment]
We are going to take care of the hosting and ops..
I created another issue for the domain part https://github.com/fabric8-launcher/launcher-quarkus/issues/9

**Comment by ia3andy** [comment]
CI is now configured to build and push the docker image:
https://circleci.com/gh/fabric8-launcher/launcher-quarkus/
on docker hub:
https://cloud.docker.com/u/fabric8/repository/docker/fabric8/launcher-quarkus

@gastaldi if you want to switch to quay instead, you just have to change this file:
https://github.com/fabric8-launcher/launcher-quarkus/blob/master/.circleci/docker.sh

We now need to sync with the SD team to:
- [ ] setup staging with automatic deployment when docker images are ready
- [ ] setup production to be released to a docker image on demand

@gastaldi do you mind taking care of this?

**Comment by ia3andy** [comment]
@gastaldi I will see with the Quarkus team to have some approximation of the audience we should have. We'll use that to setup some perf tests and maybe adjust scaling.

**Comment by gastaldi** [comment]
@ia3andy I just heard back from the Service Delivery team that the build MUST happen in their Jenkins CI instance if you're provisioning services in their domain. We can adopt the same strategy in Launcher of using CircleCI to build PRs and running tests and the CentOS build to push to staging afaik. Here are some details on how to setup that, albeit slightly outdated as said by the SD team : https://gitlab.cee.redhat.com/dtsd/devguide/blob/master/devguide.md#code-flow

**Comment by ia3andy** [comment]
@bobmcwhirter is currently transferring the quarkus.io domain so we can proceed with creating the infra.

**Comment by ia3andy** [comment]
The process of creating the infra by the SD team should start shortly..
