### ISSUE TITLE
Projects should be generated in a folder

### ISSUE THREAD

**Issue by jclingan** [fabric8-launcher/launcher-quarkus#65]
When unzipping a project, the contents are extracted into the current directory. Example:
```
$ unzip -t my-app.zip
Archive:  my-app.zip
    testing: src/main/java/           OK
    testing: src/test/java/           OK
    ...
```
Project content should be extracted into a folder based on the project name:
```
$ unzip -t my-app.zip
Archive:  my-app.zip
    testing: my-app/src/main/java/           OK
    testing: my-app/src/test/java/           OK
    ...

```

**Comment by ia3andy** [comment]
Hey @jclingan can you check that this is fixed 😁: https://code.quarkus.io/

**Comment by ia3andy** [comment]
@jclingan up?

**Comment by jclingan** [comment]
Sorry, was traveling. Verified, it works. Thx!
