### ISSUE TITLE
Provide external access to extensions.json

### ISSUE THREAD

**Issue by jeffmaury** [fabric8-launcher/launcher-quarkus#82]
For third party tools (ex Project Initializer) that will be based only on the API and not the front end, it would be fine if we can get access to the extensions list (extensions.json) through a REST endpoint.

**Comment by ia3andy** [comment]
Very good idea, I'll look into that very soon :)

**Comment by ia3andy** [comment]
@jeffmaury you now have access to the extensions list with the api as specified there:
http://editor.swagger.io/?url=https://code.quarkus.io/openapi
