### ISSUE TITLE
Choose a subdomain/subcontext in quarkus.io 

### ISSUE THREAD

**Issue by ia3andy** [fabric8-launcher/launcher-quarkus#9]
We need a landing place in quarkus.io.

- [x] Choose landing place domain or subcontext of quarkus.io (ex: start.quarkus.io)
- [ ] Setup dns to point to the hosted production Quarkus launcher (when it's ready of course)

@kenfinnigan @emmanuelbernard, do you know who is admin of the `quarkus.io` domain?

**Comment by kenfinnigan** [comment]
Might be @bobmcwhirter

**Comment by kenfinnigan** [comment]
Likely a subdomain "start.quarkus.io", but we need @n1hility and @emmanuelbernard to agree on the prefix

**Comment by bobmcwhirter** [comment]
Okie dokie. I'll also need to know the CNAME or A record you'll need.

**Comment by emmanuelbernard** [comment]
- generator
- starter
- start
- create
- extensions

**Comment by emmanuelbernard** [comment]
XceleratR
Fusion (mege core and extensions into the app)

**Comment by emmanuelbernard** [comment]
`code.quarkus.io`?

**Comment by ia3andy** [comment]
`boot.quarkus.io`
`bootstrap.quarkus.io`

**Comment by gsmet** [comment]
I wouldn't be original here, I don't see the point as we need people to memorize it easily.

So I would go with `start.quarkus.io`.

**Comment by emmanuelbernard** [comment]
@gsmet the problem is that the menu would look like this:

* Get started
* Guides
* Start
* Community
* Blog

**Comment by emmanuelbernard** [comment]
But we can get the menu name different from the dns name: we need them though.

**Comment by emmanuelbernard** [comment]
OK after careful consideration and unless someone hates it, we will go with the following

Code in the menu
and code.quarkus.io as DNS entry

**Comment by ia3andy** [comment]
Add new issue for DNS setup: https://github.com/fabric8-launcher/launcher-quarkus/issues/49
