### ISSUE TITLE
code.quarkus.io looks bizarre with iPad mini

### ISSUE THREAD

**Issue by rsvoboda** [fabric8-launcher/launcher-quarkus#96]
I looked at https://code.quarkus.io/ with iPad mini (2019) and the page looks bizarre. Looking at the same page in landscape mode is ok.

Seems code.quarkus.io expects certain screen width to work properly.
Can be simulated on desktop when the size of windows is reduce.

![IMG_0074](https://user-images.githubusercontent.com/925259/62607576-97d47d00-b8fe-11e9-97fc-5c7a869578fb.png)

![IMG_0075](https://user-images.githubusercontent.com/925259/62607632-b175c480-b8fe-11e9-9bdd-2d57716b9cbf.png)

**Comment by ia3andy** [comment]
The mobile design is a workaround until we implement it (to avoid bad rendering on small devices), for now, it shows the list of extensions..
https://github.com/fabric8-launcher/launcher-quarkus/issues/33

**Comment by rsvoboda** [comment]
ok, thanks

**Comment by ia3andy** [comment]
@rsvoboda 👍

I was just thinking about adding an info box to tell the user:
"On mobile devices, you can look at the list of extensions, If you wish to generate code, try it with your desktop browser..."

**Comment by ia3andy** [comment]
@rsvoboda I added the info: 
https://github.com/fabric8-launcher/launcher-quarkus/pull/98
